#!/usr/bin/bash

function write_head() {
  mv $1 $1.temp
  echo "//" > $1
  echo "// DON'T EDIT. THIS FILE HAS BEEN GENERATED BY wayland-scanner++" >> $1
  echo "//" >> $1
  echo >> $1
  cat $1.temp >> $1
  rm $1.temp
}

function generate_protocol() {
  wayland-scanner++ -x wayland-client-protocol-extra.hpp $1 $2.h $2.cpp
  write_head $2.h
  write_head $2.cpp
}

generate_protocol wlr-foreign-toplevel-management-unstable-v1.xml toplevel
generate_protocol wlr-layer-shell-unstable-v1.xml layer-shell
